### ISSUE TITLE
在ipad中打开失败。

### ISSUE THREAD

**Issue by anki-cat** [ntwo1980/AnkiMindMap#1]
在github上下载卡包。导入后，显示空白。请问是什么原因呢？

**Comment by anki-cat** [comment]
> 在github上下载卡包。导入后，显示空白。请问是什么原因呢？（正面与背面都空白，一无所有(≧ω≦)）

**Comment by ntwo1980** [comment]
没在ipad上用过。目前只在windows上用过。

**Comment by anki-cat** [comment]
噢噢。感谢老哥解答。老哥做的模版电脑上用的超棒(^з^)-☆
